[package]
name = "projects_client"
version = "0.3.2"
edition = "2021"

[dependencies]
axum = { version = "0.7.9", features = ["multipart"] }
reqwest = "0.12.9"
prost = { version = "0.13.3" }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"