[package]
name = "projects_client"
version = "0.3.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.5", features = ["multipart"] }
reqwest = "0.12.7"
prost = { version = "0.13.1" }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"